version: "3.8"

services:
  hilbert-main:
    image: hilbert-main
    environment:
      SPRING_PROFILES_ACTIVE: docker-dev 
      SPRING_DATASOURCE_URL: ${DATABASE_URL_DEV}
      SPRING_DATASOURCE_USERNAME: ${DATABASE_USER_DEV}
      SPRING_DATASOURCE_PASSWORD: ${DATABASE_PASSWORD_DEV}
      JWT_SECRET: ${JWT_SECRET_DEV}
      HILBERT_ML_API_KEY: ${HILBERT_ML_API_KEY_DEV}
      HILBERT_ML_API_URL: ${HILBERT_ML_API_URL_DEV}
      FRONTEND_API_URL: ${FRONTEND_API_URL_DEV}
      
    ports:
      - "8080:8080"
    networks:
      - app-network
    depends_on:
      - hilbert-ml

  hilbert-ml:
    image: hilbert-ml
    environment:
      API_KEY: ${HILBERT_ML_API_KEY_DEV}
    ports:
      - "5000:5000"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge